//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.21 at 03:14:15 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.spring.soap.api/loaneligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package api.soap.spring.loaneligibility;
